### ISSUE TITLE
Animating shadows and corner radii

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-experiments-js#17]
What's the right way to animate a change in shadows or corner radius?
- Just change the `drop-shadow` or `box-shadow` property and let the browser repaint on every frame.
- Create a new DOM element for every frame of the animation and treat them like a sprite sheet, moving a new one into view on every frame. (Non-trivial because of #16)
- Replace the transitioning element with a 9-patch during the transition and translate/scale the patches appropriately.
  - I think I tried this and making the patches and moving them around was more expensive than just letting the element repaint, but I don't think I got it to the point where the patches weren't repainting.

Perhaps the answer changes depending on the number of DOM elements transitioning, or on their complexity.  Perhaps it varies based on user hardware.

**Comment by appsforartists** [comment]
The same question (and perhaps the same answer) exists for corner/border radius.

**Comment by jverkoey** [comment]
I believe that this is resolved by latest spec.

**Comment by appsforartists** [comment]
This issue is a reminder to find the best platform-specific sorcery for performantly animating properties that cause repaints.  It may be orthogonal to the spec, but I don't think it's resolved by it.

**Comment by tofuness** [comment]
Idea using `:after` and hardware accelerated properties:

```
.element {
  /* ... */
}
.element:after {
  box-shadow: 0 0 10px #000;
  transform: scale(0);
  transform-origin: center center;
  transition: 1s ease all;
}
.element:hover:after {
  transform: scale(1);
}
```

Problem: If we wan't to transition `box-shadow` from `0 0 0` to `5px 5px 10px`, how do we determine what `transform` values to use?

**Comment by appsforartists** [comment]
I made a pen last week to experiment with this idea: https://codepen.io/appsforartists/pen/gGpaQR

I didn't noticed enough of a perf impact on repainting shadows+corners to care (even on phone hardware).  Keeping this idea in the back of my head if it becomes relevant, but for now, 🚪.
